# coding: utf-8

# flake8: noqa
"""
    Book Reader API

    API for a book reading application  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vlasovaru931@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.book import Book
