# coding: utf-8

"""
    Book Reader API

    API for a book reading application  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vlasovaru931@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.book_api import BookApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBookApi(unittest.TestCase):
    """BookApi unit test stubs"""

    def setUp(self):
        self.api = BookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_book(self):
        """Test case for add_book

        Add a new book  # noqa: E501
        """
        pass

    def test_delete_book(self):
        """Test case for delete_book

        Delete a book  # noqa: E501
        """
        pass

    def test_get_all_books(self):
        """Test case for get_all_books

        Get all books  # noqa: E501
        """
        pass

    def test_get_book(self):
        """Test case for get_book

        Get a book  # noqa: E501
        """
        pass

    def test_update_book(self):
        """Test case for update_book

        Update a book  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
